CREATE TABLE IF NOT EXISTS `users` (
	`id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`username` VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS `things` (
	`id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`id_user` INTEGER NOT NULL,
	`name` VARCHAR(255) NOT NULL,
	CONSTRAINT `fk_things_users` FOREIGN KEY (`id_user`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS `commons` (
	`id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS `users_commons` (
	`id` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`id_user` INTEGER NOT NULL,
	`id_common` INTEGER NOT NULL,
	CONSTRAINT `fk_users_commons_users` FOREIGN KEY (`id_user`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT `fk_users_commons_commonds` FOREIGN KEY (`id_common`) REFERENCES `commons` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
);